import {RF, SCREEN_HEIGHT} from '@theme';
import {StyleSheet} from 'react-native';

const useStyles = (colors: any) =>
  StyleSheet.create({
    i: {
      width: RF(50),
      height: RF(50),
      resizeMode: 'contain',
      elevation: 2,
    },
    v: {
      marginHorizontal: RF(5),
      backgroundColor: 'white',
    },
    inputContainer: {
      borderWidth: 1,
      borderColor: '#1a4b8a',
      borderRadius: 10,
      backgroundColor: '#fff',
      padding: 10,
      marginTop: RF(8),
    },
    textInput: {
      height: 100,
      fontSize: 16,
      color: '#000',
      paddingTop: 0,
    },
    image: {width: RF(20), height: RF(20), resizeMode: 'contain'},
    imgView: {
      borderWidth: 1,
      width: '100%',
      borderRadius: RF(40),
      alignItems: 'center',
      borderStyle: 'dashed',
      paddingVertical: 15,
      marginTop: RF(20),
    },
    down: {
      width: '100%',
      borderColor: 'black',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      // zIndex: 100,
    },
    scroll: {
      margin: RF(20),
      // marginRight: 0,
      // padding: RF(20),
      marginBottom: 100,
      height: SCREEN_HEIGHT / 1.5,
    },
    ml: {marginLeft: RF(10)},
    pressable: {
      padding: RF(10),
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'white',
      elevation: 5,
      marginHorizontal: RF(8),
      marginVertical: RF(4),
    },
    main: {
      flex: 1,
      marginVertical: RF(16),
      marginHorizontal: RF(8),
    },
    img: {
      width: RF(90),
      height: RF(88),
      borderRadius: 10,
      resizeMode: 'contain',
    },
    btn: {
      width: RF(14),
      height: RF(14),
      resizeMode: 'contain',
      tintColor: 'white',
    },
    btnV: {
      width: RF(48),
      height: RF(48),
      borderRadius: 100,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors?.bluE,
      alignSelf: 'flex-end',
      position: 'absolute',
      bottom: 100,
      right: 10,
      elevation: 2,
    },
    view: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginVertical: RF(5),
      marginBottom: RF(10),
    },
    absolute: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
      // zIndex: -100,
    },
    forDrop: {
      // borderWidth: 1,
      backgroundColor: '#fff',
      borderColor: 'gray',
      elevation: 1,
      right: RF(1),
      borderTopRightRadius: 10,
      borderTopLeftRadius: 10,
      paddingHorizontal: 5,
    },

    rectangleCard: {
      borderWidth: 1,
      width: '100%',
      height: RF(56),
      borderRadius: 8,
      borderColor: '#0D47A1',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: RF(8),
      flexDirection: 'row',
      marginTop: RF(10),
    },
    imgCard: {
      height: RF(48),
      width: RF(48),
      overflow: 'hidden',
      borderRadius: 8,
      borderWidth: 1,
    },
    icon: {height: RF(16), width: RF(16), resizeMode: 'contain'},
  });

export default useStyles;
